name: Build and Deploy to Development Environment in Azure

on:
  push:
    branches: main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./joke
          push: true
          tags: |
            fjukstad/joke:1.0.${{ github.run_number	}}
            fjukstad/joke:latest
      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: Azure/aci-deploy@v1
        with:
          resource-group: bfj-test
          dns-name-label: joke-dev
          image: fjukstad/joke:1.0.${{ github.run_number	}}
          name: joke-dev
          location: "westeurope"
          ports: "80 443"
          environment-variables: DOTNET_ENVIRONMENT=Development
